### ISSUE TITLE
API changed in patch version (1.3.1)

### ISSUE THREAD

**Issue by BSchilperoort** [ecmwf-projects/cads-api-client#81]
In #69 the order of the arguments to cads_api_client.ApiClient changed (maybe unintentionally?).

Instead of (key, url), the order changed to (url, key). The changed code was released as part of version 1.3.1. This broke any other code that did not use the arguments as kwargs, such as era5cli (https://github.com/eWaterCycle/era5cli/issues/168).

**Comment by malmans2** [comment]
Hi there, sorry about that!
It was intentional to align with `cdsapi`. See: https://github.com/ecmwf-projects/cads-api-client/issues/75

Please not that at the moment `cads-api-client` is not stable.

**Comment by BSchilperoort** [comment]
> Please not that at the moment `cads-api-client` is not stable.

The version number makes it seem like it would be. Could you add this disclaimer clearly in the README?
